### PR TITLE
Create function to set detection threshold for instance segmentation

### PR DESCRIPTION
**Pull request by footballdaniel**
Dear Ayoola,

Thanks for creating pixellib! I have a small pull request to change the detection threshold for the instance segmentation.

If you accept the pull request, I will be able to call pixellib with:
```python
segment_video = instance_segmentation()
segment_video.set_detection_confidence(0.1) # new strategy
segment_video.load_model("mask_rcnn_coco.h5")
segment_video.segmentImage("frame.png", output_image_name = "out.jpg")
``` 
Please let me know if you want me to make any changes. Best regards, Daniel

### CODE REVIEW

**Comment by ayoolaolafenwa** [comment]
> Dear Ayoola,
> 
> Thanks for creating pixellib! I have a small pull request to change the detection threshold for the instance segmentation.
> 
> If you accept the pull request, I will be able to call pixellib with:
> 
> ```python
> segment_video = instance_segmentation()
> segment_video.set_detection_confidence(0.1) # new strategy
> segment_video.load_model("mask_rcnn_coco.h5")
> segment_video.segmentImage("frame.png", output_image_name = "out.jpg")
> ```
> 
> Please let me know if you want me to make any changes. Best regards, Daniel

Thank you @footballdaniel. I will review and get back to you.

**Comment by ayoolaolafenwa** [comment]
@footballdaniel  I added minor changes to your PR. I removed the function and added the changes to the **load_model** function.

I moved your code

``` python
def set_detection_confidence(self, confidence):
   coco_config.DETECTION_MIN_CONFIDENCE = confidence
```
to the **load_model** function.

``` python
#use your parameter confidence to set value of detection confidence 
# and set it to None to avoid errors when it is not used.
def load_model(self, model_path, confidence= None):
    self.model = MaskRCNN(mode = "inference", model_dir = self.model_dir, config = coco_config)
    self.model.load_weights(model_path, by_name= True)

     # set detection minimum confidence to the value of the confidence parameter
     if confidence is not None:
         coco_config.DETECTION_MIN_CONFIDENCE = confidence
```
**Note** I made these changes to maintain the same number of lines of code for detection while using the detection threshold. 

Thank you very much for your contribution.

**Comment by footballdaniel** [comment]
Dear Ayoola, amazing! This is exactly what I was hoping for. Thank you so much for creating pixellib :)

**Comment by footballdaniel** [comment]
Hi Ayoola, I have noticed a small bug in the last PR. We need to switch two lines.
 The confidence argument should be evaluated **before** the MaskRCNN is instantiated, otherwise the `confidence`  argument is never used:

Currently:
```python
#use your parameter confidence to set value of detection confidence 
# and set it to None to avoid errors when it is not used.
def load_model(self, model_path, confidence= None):
    self.model = MaskRCNN(mode = "inference", model_dir = self.model_dir, config = coco_config)
    self.model.load_weights(model_path, by_name= True)

     # set detection minimum confidence to the value of the confidence parameter
     if confidence is not None:
         coco_config.DETECTION_MIN_CONFIDENCE = confidence
``` 


Should be:
```python
#use your parameter confidence to set value of detection confidence 
# and set it to None to avoid errors when it is not used.
def load_model(self, model_path, confidence= None):
     # set detection minimum confidence to the value of the confidence parameter
     if confidence is not None:
         coco_config.DETECTION_MIN_CONFIDENCE = confidence

    self.model = MaskRCNN(mode = "inference", model_dir = self.model_dir, config = coco_config)
    self.model.load_weights(model_path, by_name= True)
```

Do you want me to create a new pull request for that or will you change it directly in your source?

Best regards, 
Daniel

**Comment by ayoolaolafenwa** [comment]
Thank you so much @footballdaniel I have added the changes.

**Pull request merged**
